import { defineConfig } from "tsup";

export default defineConfig({
  entry: {
    index: "src/index.ts",
    "core/index": "src/core/index.ts",
    "pipeline/index": "src/pipeline/index.ts",
    "import/markdown": "src/import/markdown.ts",
    "import/html": "src/import/html.ts",
    "import/dita": "src/import/dita.ts",
    "import/confluence": "src/import/confluence.ts",
    "import/word": "src/import/word.ts",
    "import/flare": "src/import/flare.ts",
    "import/openapi": "src/import/openapi.ts",
    "import/paligo": "src/import/paligo.ts",
    "export/markdown": "src/export/markdown.ts",
    "export/dita": "src/export/dita.ts",
    "export/html": "src/export/html.ts",
    canonical: "src/canonical.ts",
    hdita: "src/hdita.ts",
  },
  format: ["esm", "cjs"],
  dts: true,
  sourcemap: true,
  clean: true,
  splitting: true,
  treeshake: true,
  external: [
    "@tiptap/core",
    "@tiptap/html",
    "@tiptap/html/server",
    "@tiptap/starter-kit",
    "@tiptap/extension-table",
    "@tiptap/extension-table-row",
    "@tiptap/extension-table-cell",
    "@tiptap/extension-table-header",
    "@tiptap/extension-image",
    "@tiptap/extension-link",
    "@tiptap/extension-code-block-lowlight",
    "lowlight",
    "marked",
    "cheerio",
    "domhandler",
    "fast-xml-parser",
    "mammoth",
    "@apidevtools/swagger-parser",
    "js-yaml",
    "openapi-types",
  ],
});
